from dotenv import load_dotenv
from langchain_mistralai import ChatMistralAI
from langchain_community.document_loaders import TextLoader #It will load the text file and convert it into a list of documents. Each document will be represented as a string.
from langchain_core.prompts import ChatPromptTemplate#The ChatPromptTemplate class is used to create a prompt template for the chat model. It allows us to define a template for the input prompt that we will pass to the model. The template can include placeholders for dynamic content, such as the data from the text file.

load_dotenv()#The load_dotenv() function is used to load environment variables from a .env file. This is useful for keeping sensitive information, such as API keys, out of the source code. By calling load_dotenv(), we can access the environment variables defined in the .env file throughout our code.

data= TextLoader("document loaders/notes.txt") #Here, we are creating an instance of the TextLoader class and passing the path to the text file that we want to load. The load() method will read the contents of the file and return a list of documents. Each document will be represented as a string.
docs= data.load() #The load() method will read the contents of the file and return a list of documents. Each document will be represented as a string.

template=ChatPromptTemplate.from_messages([("system", "You are a helpful assistant."),
                                  ("human", "{data}")]) #The from_messages() method is used to create a prompt template from a list of messages. Each message is represented as a tuple, where the first element is the role of the message (e.g., "system", "human") and the second element is the content of the message. In this case, we have a system message that sets the context for the assistant and a human message that includes a placeholder for the data from the text file. The {data} placeholder will be replaced with the actual content of the document when we format the prompt.

model=ChatMistralAI(model="mistral-small-2506")

prompt= template.format_messages(data=docs[0].page_content) #We only want to see page content not the metadeata

print(len(prompt)) #This will print the length of the formatted prompt. The length is measured in tokens, which are the basic units of text that the model processes. The number of tokens in the prompt can affect the response generated by the model, as there may be limits on the maximum number of tokens that can be processed in a single request.

result=model.invoke(prompt) #The invoke() method will take the formatted prompt and pass it to the model for processing. The model will generate a response based on the input prompt and return it as a string.
print(result.content)